// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package logbus

// TrackLoggerConf should use NewTrackLoggerConf to initialize it
type TrackLoggerConf struct {
	tags    []string
	BiAppID string
}

// NewTrackLoggerConf new TrackLoggerConf
func NewTrackLoggerConf(opts ...TrackLoggerConfOption) *TrackLoggerConf {
	cc := newDefaultTrackLoggerConf()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogTrackLoggerConf != nil {
		watchDogTrackLoggerConf(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *TrackLoggerConf) ApplyOption(opts ...TrackLoggerConfOption) {
	for _, opt := range opts {
		opt.Apply(cc)
	}
}

// TrackLoggerConfOptionFunc option func
type TrackLoggerConfOption interface {
	Apply(cc *TrackLoggerConf)
}

var _ TrackLoggerConfOption = TrackLoggerConfOptionFunc(nil)

type TrackLoggerConfOptionFunc func(cc *TrackLoggerConf)

func (f TrackLoggerConfOptionFunc) Apply(cc *TrackLoggerConf) {
	f(cc)
}

// WithTags 打点日志标签，必须提供，至少一个标签
func WithTags(v ...string) TrackLoggerConfOptionFunc {
	return func(cc *TrackLoggerConf) {
		cc.tags = v
	}
}

// AppendTags 打点日志标签，必须提供，至少一个标签
func AppendTags(v ...string) TrackLoggerConfOptionFunc {
	return func(cc *TrackLoggerConf) {
		cc.tags = append(cc.tags, v...)
	}
}

// WithBiAppID bi appid, 比如 "gof.global.prod"
func WithBiAppID(v string) TrackLoggerConfOptionFunc {
	return func(cc *TrackLoggerConf) {
		cc.BiAppID = v
	}
}

// InstallTrackLoggerConfWatchDog the installed func will called when NewTrackLoggerConf  called
func InstallTrackLoggerConfWatchDog(dog func(cc *TrackLoggerConf)) { watchDogTrackLoggerConf = dog }

// watchDogTrackLoggerConf global watch dog
var watchDogTrackLoggerConf func(cc *TrackLoggerConf)

// setTrackLoggerConfDefaultValue default TrackLoggerConf value
func setTrackLoggerConfDefaultValue(cc *TrackLoggerConf) {
	for _, opt := range [...]TrackLoggerConfOptionFunc{
		WithTags(nil...),
		WithBiAppID(""),
	} {
		opt(cc)
	}
}

// newDefaultTrackLoggerConf new default TrackLoggerConf
func newDefaultTrackLoggerConf() *TrackLoggerConf {
	cc := &TrackLoggerConf{}
	setTrackLoggerConfDefaultValue(cc)
	return cc
}

// all getter func
func (cc *TrackLoggerConf) GetTags() []string  { return cc.tags }
func (cc *TrackLoggerConf) GetBiAppID() string { return cc.BiAppID }

// TrackLoggerConfVisitor visitor interface for TrackLoggerConf
type TrackLoggerConfVisitor interface {
	GetTags() []string
	GetBiAppID() string
}

// TrackLoggerConfInterface visitor + ApplyOption interface for TrackLoggerConf
type TrackLoggerConfInterface interface {
	TrackLoggerConfVisitor
	ApplyOption(...TrackLoggerConfOption)
}
