// Code generated by optiongen. DO NOT EDIT.
// optiongen: github.com/timestee/optiongen

package logbus

// TruncateWriteSyncerOption should use NewTruncateWriteSyncerOption to initialize it
type TruncateWriteSyncerOption struct {
	TruncateMaxSize int
	MsgPrefixLen    int
	MsgSuffixLen    int
}

// NewTruncateWriteSyncerOption new TruncateWriteSyncerOption
func NewTruncateWriteSyncerOption(opts ...TruncateWriteSyncerOptionOption) *TruncateWriteSyncerOption {
	cc := newDefaultTruncateWriteSyncerOption()
	for _, opt := range opts {
		opt.Apply(cc)
	}
	if watchDogTruncateWriteSyncerOption != nil {
		watchDogTruncateWriteSyncerOption(cc)
	}
	return cc
}

// ApplyOption apply multiple new option
func (cc *TruncateWriteSyncerOption) ApplyOption(opts ...TruncateWriteSyncerOptionOption) {
	for _, opt := range opts {
		opt.Apply(cc)
	}
}

// TruncateWriteSyncerOptionOptionFunc option func
type TruncateWriteSyncerOptionOption interface {
	Apply(cc *TruncateWriteSyncerOption)
}

var _ TruncateWriteSyncerOptionOption = TruncateWriteSyncerOptionOptionFunc(nil)

type TruncateWriteSyncerOptionOptionFunc func(cc *TruncateWriteSyncerOption)

func (f TruncateWriteSyncerOptionOptionFunc) Apply(cc *TruncateWriteSyncerOption) {
	f(cc)
}

// WithTruncateMaxSize 超出长度限制时输出日志的标志字段，便于检索和过滤，默认800KB
func WithTruncateMaxSize(v int) TruncateWriteSyncerOptionOptionFunc {
	return func(cc *TruncateWriteSyncerOption) {
		cc.TruncateMaxSize = v
	}
}

// WithMsgPrefixLen 截断时保留的前缀长度，默认4KB
func WithMsgPrefixLen(v int) TruncateWriteSyncerOptionOptionFunc {
	return func(cc *TruncateWriteSyncerOption) {
		cc.MsgPrefixLen = v
	}
}

// WithMsgSuffixLen 截断时保留的后缀长度，默认4KB
func WithMsgSuffixLen(v int) TruncateWriteSyncerOptionOptionFunc {
	return func(cc *TruncateWriteSyncerOption) {
		cc.MsgSuffixLen = v
	}
}

// InstallTruncateWriteSyncerOptionWatchDog the installed func will called when NewTruncateWriteSyncerOption  called
func InstallTruncateWriteSyncerOptionWatchDog(dog func(cc *TruncateWriteSyncerOption)) {
	watchDogTruncateWriteSyncerOption = dog
}

// watchDogTruncateWriteSyncerOption global watch dog
var watchDogTruncateWriteSyncerOption func(cc *TruncateWriteSyncerOption)

// setTruncateWriteSyncerOptionDefaultValue default TruncateWriteSyncerOption value
func setTruncateWriteSyncerOptionDefaultValue(cc *TruncateWriteSyncerOption) {
	for _, opt := range [...]TruncateWriteSyncerOptionOptionFunc{
		WithTruncateMaxSize(DefaultTruncateMaxSize),
		WithMsgPrefixLen(DefaultTruncateMsgPrefixLen),
		WithMsgSuffixLen(DefaultTruncateMsgSuffixLen),
	} {
		opt(cc)
	}
}

// newDefaultTruncateWriteSyncerOption new default TruncateWriteSyncerOption
func newDefaultTruncateWriteSyncerOption() *TruncateWriteSyncerOption {
	cc := &TruncateWriteSyncerOption{}
	setTruncateWriteSyncerOptionDefaultValue(cc)
	return cc
}

// all getter func
func (cc *TruncateWriteSyncerOption) GetTruncateMaxSize() int { return cc.TruncateMaxSize }
func (cc *TruncateWriteSyncerOption) GetMsgPrefixLen() int    { return cc.MsgPrefixLen }
func (cc *TruncateWriteSyncerOption) GetMsgSuffixLen() int    { return cc.MsgSuffixLen }

// TruncateWriteSyncerOptionVisitor visitor interface for TruncateWriteSyncerOption
type TruncateWriteSyncerOptionVisitor interface {
	GetTruncateMaxSize() int
	GetMsgPrefixLen() int
	GetMsgSuffixLen() int
}

// TruncateWriteSyncerOptionInterface visitor + ApplyOption interface for TruncateWriteSyncerOption
type TruncateWriteSyncerOptionInterface interface {
	TruncateWriteSyncerOptionVisitor
	ApplyOption(...TruncateWriteSyncerOptionOption)
}
